// 태현씨 qna 게시판
export const REQUEST_QNA_BOARD_LIST_TO_SPRING = 'REQUEST_QNA_BOARD_LIST_TO_SPRING'
export const REQUEST_QNA_BOARD_TO_SPRING = 'REQUEST_QNA_BOARD_TO_SPRING'

// 태현씨 qna 게시판 - 댓글 기능
export const REQUEST_QNA_COMMENT_LIST_FROM_SPRING = 'REQUEST_QNA_COMMENT_LIST_FROM_SPRING'

// 진우씨 상품 게시판
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'
export const REQUEST_ALL_PRODUCT_TO_SPRING = 'REQUEST_ALL_PRODUCT_TO_SPRING'


// 태현씨 장바구니 
export const REQUEST_CART_LIST_FROM_SPRING = "REQUEST_CART_LIST_FROM_SPRING"

// // 지영씨 기부 페이지, 마이페이지-나의기부내역
// export const REQUEST_MY_DONATE_VISIT_LIST_TO_SPRING = 'REQUEST_MY_DONATE_VISIT_LIST_TO_SPRING'
// export const REQUEST_MY_DONATE_VISIT_READ_TO_SPRING = 'REQUEST_MY_DONATE_VISIT_READ_TO_SPRING'

// // 태현씨 공지게시판 -> 지영씨
// export const REQUEST_NOTICE_BOARD_LIST_TO_SPRING = 'REQUEST_NOTICE_BOARD_LIST_TO_SPRING'
// export const REQUEST_NOTICE_BOARD_TO_SPRING = 'REQUEST_NOTICE_BOARD_TO_SPRING'

