// 태현씨 qna 게시판
export const REQUEST_QNA_BOARD_LIST_TO_SPRING = 'REQUEST_QNA_BOARD_LIST_TO_SPRING'
export const REQUEST_QNA_BOARD_TO_SPRING = 'REQUEST_QNA_BOARD_TO_SPRING'

// 태현씨 qna 게시판 - 댓글 기능
export const REQUEST_QNA_COMMENT_LIST_FROM_SPRING = 'REQUEST_QNA_COMMENT_LIST_FROM_SPRING'

// 진우씨 상품 게시판
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'
export const REQUEST_ALL_PRODUCT_TO_SPRING = 'REQUEST_ALL_PRODUCT_TO_SPRING'

