// mypageMutation-Types.js
export const SET_MY_PAGE_DATA = 'SET_MY_PAGE_DATA';
export const UPDATE_MY_PAGE_DATA = 'UPDATE_MY_PAGE_DATA';
export const SET_IS_CURRENT_PASSWORD_CORRECT = 'SET_IS_CURRENT_PASSWORD_CORRECT';
export const SET_PASSWORD_UPDATE_STATUS = 'SET_PASSWORD_UPDATE_STATUS';